/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cardapio`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sobre`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cardapio/bebidas` | `/cardapio/bebidas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cardapio/doces` | `/cardapio/doces`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cardapio/salgados` | `/cardapio/salgados`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sobre/cliente` | `/sobre/cliente`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sobre/equipe` | `/sobre/equipe`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/cardapio`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/sobre`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cardapio/bebidas` | `/cardapio/bebidas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cardapio/doces` | `/cardapio/doces`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cardapio/salgados` | `/cardapio/salgados`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sobre/cliente` | `/sobre/cliente`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sobre/equipe` | `/sobre/equipe`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/cardapio${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/sobre${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cardapio/bebidas${`?${string}` | `#${string}` | ''}` | `/cardapio/bebidas${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cardapio/doces${`?${string}` | `#${string}` | ''}` | `/cardapio/doces${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cardapio/salgados${`?${string}` | `#${string}` | ''}` | `/cardapio/salgados${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sobre/cliente${`?${string}` | `#${string}` | ''}` | `/sobre/cliente${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sobre/equipe${`?${string}` | `#${string}` | ''}` | `/sobre/equipe${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/cardapio`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/sobre`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cardapio/bebidas` | `/cardapio/bebidas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cardapio/doces` | `/cardapio/doces`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cardapio/salgados` | `/cardapio/salgados`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sobre/cliente` | `/sobre/cliente`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sobre/equipe` | `/sobre/equipe`; params?: Router.UnknownInputParams; };
    }
  }
}
