/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bebidas`; params?: Router.UnknownInputParams; } | { pathname: `/cardapio`; params?: Router.UnknownInputParams; } | { pathname: `/doces`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/salgados`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cliente` | `/cliente`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/equipe` | `/equipe`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/bebidas`; params?: Router.UnknownOutputParams; } | { pathname: `/cardapio`; params?: Router.UnknownOutputParams; } | { pathname: `/doces`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/salgados`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/cliente` | `/cliente`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/equipe` | `/equipe`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/bebidas${`?${string}` | `#${string}` | ''}` | `/cardapio${`?${string}` | `#${string}` | ''}` | `/doces${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/salgados${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/cliente${`?${string}` | `#${string}` | ''}` | `/cliente${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/equipe${`?${string}` | `#${string}` | ''}` | `/equipe${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/bebidas`; params?: Router.UnknownInputParams; } | { pathname: `/cardapio`; params?: Router.UnknownInputParams; } | { pathname: `/doces`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/salgados`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/cliente` | `/cliente`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/equipe` | `/equipe`; params?: Router.UnknownInputParams; };
    }
  }
}
